# Generated by Django 5.1.2 on 2024-11-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronomyc',
            field=models.CharField(default='User', max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='User', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='User', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='User', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default='User', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
