# Generated by Django 5.1.2 on 2024-11-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronomyc',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
