# Generated by Django 5.0.3 on 2024-11-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_patronomyc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bin", models.CharField(max_length=100, verbose_name="bin")),
                ("amount", models.CharField(max_length=100, verbose_name="amount")),
                (
                    "shoppercountrycode",
                    models.CharField(max_length=100, verbose_name="shoppercountrycode"),
                ),
                (
                    "cardverificationcodesupplied",
                    models.CharField(
                        max_length=100, verbose_name="cardverificationcodesupplied"
                    ),
                ),
                (
                    "cvcresponsecode",
                    models.CharField(max_length=100, verbose_name="txvariantcode"),
                ),
                ("txvariantcode", models.CharField(max_length=100, verbose_name="bin")),
                ("Day", models.CharField(max_length=100, verbose_name="Day")),
                ("Month", models.CharField(max_length=100, verbose_name="Month")),
                (
                    "time_in_seconds",
                    models.CharField(max_length=100, verbose_name="time_in_seconds"),
                ),
                (
                    "issuercountrycode",
                    models.CharField(max_length=100, verbose_name="issuercountrycode"),
                ),
            ],
        ),
    ]
