# Generated by Django 5.1.2 on 2024-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('desc', models.CharField(max_length=100, verbose_name='desc')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/services')),
            ],
        ),
    ]
