# Generated by Django 5.1.3 on 2024-12-24 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_services_updated_at_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отчёта')),
                ('date', models.DateField(verbose_name='Дата отчёта')),
                ('fraud_status', models.CharField(choices=[('not_fraud', 'Транзакция не мошенническая'), ('fraud', 'Транзакция мошенническая')], default='not_fraud', max_length=10, verbose_name='Статус транзакции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
